Add type-definition
janis-commerce/api-get pull request #6
Opened 2021-11-29 13:24 UTC by moruezabal

**Requerimiento:**
Se requiere agreagar estos TypeDef al package de API-Get

**Historia de usuario**
https://fizzmod.atlassian.net/browse/JCN-331

**Subtarea**
https://fizzmod.atlassian.net/browse/JCN-341

2021-11-30 18:52 UTC, MarianoFndz approved these changes

2021-12-01 21:59 UTC, gastonpereyra commented on lib/api-get.js
> +	 * Validate the model, extracted from the parsed endpoint
:thinking:  Creo que falta el 

```
* @returns {void}
```
Que usaste en el `process` .

Y de pasó en todos los metodos que no hay un return también se podría agregar. De esa manera quedan todos parejos.

2021-12-01 22:04 UTC, gastonpereyra commented on lib/api-get.js
> +	 * Validate the model, extracted from the parsed endpoint
Como descripción le pondría:

> "Realiza validaciones antes de procesar. Settea el Modelo a usar y parsea el Endpoint. Importante, no es aconsejable sobreescribirlo"

2021-12-01 22:05 UTC, gastonpereyra commented on lib/api-get.js
>  class ApiGet extends API {
Este package quedó viejito.. aca podriamos exportarlo de una 

```js
module.exports = class ApiGet extends API {

```

2021-12-01 22:09 UTC, gastonpereyra commented on lib/helpers/endpoint-parser.js
> +/**
Esto deberia estar en el metodo no en la definición de la clase

2021-12-01 22:15 UTC, gastonpereyra commented on package.json
>    },
Pongo el comentario aca porque no puedo ponerlo en la linea que va... que sería como en la 10/11.

Falta el Script  `build-types` que se usa en el action de publicar (ese que agregaste).

```
"build-types": "tsc lib/index.js --declaration --allowJs --emitDeclarationOnly --outDir types",
```

Sin esto va a explotar el Action y no se van a buildear los TypeDef

2021-12-01 22:17 UTC, gastonpereyra commented on lib/api-get.js
> +	 * It makes the query to the DB with the filters and params obtained from the endpoint
Como en el Validate, habría qu aclarar que es un Importante no modificar este método.

2021-12-01 22:26 UTC, gastonpereyra commented on lib/api-get.js
>  		this._validateModel();
:bulb: 

Esto no estaba en el ticket :smiling_imp:  pero me parece copado tenerlo.

Cómo puse en un comentario anterior, el validate no hay que modificarlo. Pero para agregar validaciones extras, como esta ahora el package no queda otra que hacerlo.

Para solucionar esto vamos a agregar un nuevo método.. 

Este método lo vamos a llamar `postValidate` .

> Cómo lo agregamos ?

```js
	async validate() {

		this._parseEndpoint();
		this._validateModel();
		
		return this.postValidate(); // ----> agregamos esto en validate
	}
	
	// --> aca hay que agregarlo el TypeDef con la descripción "Es para realizar validaciones extra"
	async postValidate() {
		return;
	}
```

> Porqué escribir el método aunque no haga nada ? 

Para poder poner el typeDef y el editor lo pueda sugerir

2021-12-01 22:38 UTC, gastonpereyra commented on lib/api-get.js
>  	async process() {
Aca falta algo, hay métodos que tienen un if para ejecutarse o no..

* `_parseFilters`
* `fieldsToSelect`
* `postGetValidate`
* `format`

Estos métodos son opcionales.. pero para que puedan ser sugeridos usando TypeDef hay que escribirlos en el código, agregar el TypeDef, y mantener la compatibilidad..

:bulb: Para  `_parseFilters` , `postGetValidate` , `format`, hay que hacerlo si o si.. pongo el ejemplo del format pero es para los 3

Ahora
```
	async process {
		// resto del codigo

		const response = this.format ? await this.format(this.record) : this.record;
		this.setBody(response);
	}
```

Cambió

```
	async process {
		// resto del codigo

		const response = await this.format(this.record);
		this.setBody(response);
	}

	// ----> aca el TypeDef
	async format(record) {
		return record
	}
```

Para cada caso fijarse en el README cual es su función.

:warning: Para `fieldsToSelect` deberia pasar lo mismo PERO, es un caso especial, porque agrega un dato a un filtro.. y no se puede hacer lo mismo que los otros.. no sé como hacerlo y que quede bien.. asi que aca no lo haria, lo dejaria como esta..

2021-12-01 22:39 UTC, gastonpereyra commented on lib/api-get.js
>  	async process() {
Dicho se ade pasó los typeDef de estos son más importantes que casi el resto de métodos.. porque son los que vamos a usar

2021-12-01 22:41 UTC, gastonpereyra commented on lib/api-get.js
>  		const { modelName, recordId, parents } = EndpointParser.parse(this.endpoint);
Aca vamos a hacer una modificación importante, que hace mucho espero que haya una oportunidad para meterla

```
if(!this.modelName)
      this.modelName = modelName;
```

> Por qué ?

Porque de esta manera podemos usar la API Get desde cualquier lado y hacia cualquier modelo.. sin esto estamos limitados a poner los archivos en las carpetas correctas y eso a la larga te limita

2021-12-01 22:42 UTC, gastonpereyra requested changes
Deje varios cambios y mejoras..

Y una cosa más falta el Changelog

2021-12-07 15:09 UTC, gastonpereyra approved these changes
Listorti

2021-12-13 13:29 UTC, juanhapes approved these changes

2021-12-13 14:06 UTC, merged